#!/bin/bash

input_archive="$HOME/.config/youtube-dl/input.txt"

url_array=()
youtube-dl --version
if [[ -n "${1}" ]]
then
    url_array+=("${1}")
    printf "\n[arg] %s\n" "${1}"
fi
while true
do
    url=""
    char=""
    while read -t 1 -n 1 -s -r char || [ -z "${url}" ]
    do
        url+="${char}"
        if [ "${#url_array[@]}" -ne 0 ] && ! jobs %% &> /dev/null
        then
            printf "%s\n" "${url_array[0]}" >> "${input_archive}"
            printf "\n[1 / %d] %s\n" "${#url_array[@]}" "${url_array[0]}"
            youtube-dl "${url_array[0]}" &
            url_array=("${url_array[@]:1}")
        fi
    done
    url_array+=("${url}")
    if ! jobs %% &> /dev/null
    then
        printf "\n[start] %s\n" "${url}"
    else
        printf "\n\n[queue %d] %s\n\n" "${#url_array[@]}" "${url}"
    fi
done
