#!/bin/bash

input_archive="$HOME/.config/youtube-dl/input.txt"

trap ctrl_c INT

function ctrl_c() {
    stty echo
    kill %1 &> /dev/null 2>&1
    printf "\n"
    for drop in "${url_array[@]}"
    do
        printf "[drop] %s\n" "${drop}"
    done
    exit
}

url_array=()
if [[ -n "${1}" ]]
then
    youtube-dl --version
    url_array+=("${1}")
    printf "\n[arg] %s\n" "${1}" &
else
    youtube-dl --version &
fi
pid=$!
while true
do
    url=""
    char=""
    while read -t 1 -n 1 -s -r char || [ -z "${url}" ]
    do
        url+="${char}"
        if [ "${#url_array[@]}" -ne 0 ] && ! ps -p "${pid}" > /dev/null
        then
            printf "%s\n" "${url_array[0]}" >> "${input_archive}"
            printf "\n[1 / %d] %s\n" "${#url_array[@]}" "${url_array[0]}"
            youtube-dl "${url_array[0]}" &
            pid=$!
            url_array=("${url_array[@]:1}")
        fi
    done
    url_array+=("${url}")
    if ! ps -p "${pid}" > /dev/null
    then
        printf "\n[start] %s\n" "${url}"
    else
        printf "\n\n[queue %d] %s\n\n" "${#url_array[@]}" "${url}"
    fi
done
