#!/bin/bash

url_array=()
if [[ -n "${1}" ]]
then
    youtube-dl --version
    printf "\n[arg] %s\n\n" "${1}"
    youtube-dl "${1}" &
else
    youtube-dl --version &
fi
pid=$!
while true
do
    url=""
    char=""
    while read -t 1 -n 1 -s -r char || [ -z "${url}" ]
    do
        url+="${char}"
        if [ "${#url_array[@]}" -ne 0 ] && ! ps -p "${pid}" > /dev/null
        then
            printf "\n"
            youtube-dl "${url_array[0]}" &
            pid=$!
            url_array=("${url_array[@]:1}")
        fi
    done
    url_array+=("${url}")
    if ! ps -p "${pid}" > /dev/null
    then
        printf "\n[start] %s\n" "${url}"
    else
        printf "\n\n[queue %d] %s\n\n" "${#url_array[@]}" "${url}"
    fi
done
